from cartography.rules.data.rules import RULES

EXPECTED_ISO27001_REQUIREMENTS = {
    "cis_gcp_3_1_default_network": {"8.20", "8.22"},
    "cis_gcp_3_3_dnssec_enabled": {"8.20"},
    "cis_gcp_3_4_dnssec_no_rsasha1_ksk": {"8.24"},
    "cis_gcp_3_5_dnssec_no_rsasha1_zsk": {"8.24"},
    "cis_gcp_3_6_unrestricted_ssh": {"8.20"},
    "cis_gcp_3_7_unrestricted_rdp": {"8.20"},
    "cis_gcp_3_8_vpc_flow_logs": {"8.15", "8.16"},
    "cis_gcp_4_1_default_service_account": {"5.16"},
    "cis_gcp_4_2_default_service_account_full_api": {"5.18", "8.2"},
    "cis_gcp_4_3_block_project_wide_ssh_keys": {"8.5"},
    "cis_gcp_4_4_oslogin_enabled": {"8.5"},
    "cis_gcp_4_5_serial_ports_disabled": {"8.3"},
    "cis_gcp_4_6_ip_forwarding": {"8.20"},
    "cis_gcp_4_8_shielded_vm": {"8.9"},
    "cis_gcp_4_9_public_ip": {"8.20"},
    "cis_gcp_4_11_confidential_compute": {"8.24"},
    "cis_gcp_5_2_bucket_uniform_access": {"8.3"},
    "cis_gcp_6_1_2_cloudsql_mysql_skip_show_database": {"8.9"},
    "cis_gcp_6_1_3_cloudsql_mysql_local_infile": {"8.9"},
    "cis_gcp_6_2_1_cloudsql_postgres_log_error_verbosity": {"8.9"},
    "cis_gcp_6_2_2_cloudsql_postgres_log_connections": {"8.9"},
    "cis_gcp_6_2_3_cloudsql_postgres_log_disconnections": {"8.9"},
    "cis_gcp_6_2_5_cloudsql_postgres_log_min_messages": {"8.9"},
    "cis_gcp_6_2_6_cloudsql_postgres_log_min_error_statement": {"8.9"},
    "cis_gcp_6_2_7_cloudsql_postgres_log_min_duration_statement": {"8.9"},
    "cis_gcp_6_2_8_cloudsql_postgres_enable_pgaudit": {"8.9"},
    "cis_gcp_6_3_1_cloudsql_sqlserver_external_scripts": {"8.9"},
    "cis_gcp_6_3_2_cloudsql_sqlserver_cross_db_ownership": {"8.9"},
    "cis_gcp_6_3_3_cloudsql_sqlserver_user_connections": {"8.9"},
    "cis_gcp_6_3_4_cloudsql_sqlserver_user_options": {"8.9"},
    "cis_gcp_6_3_5_cloudsql_sqlserver_remote_access": {"8.9"},
    "cis_gcp_6_3_6_cloudsql_sqlserver_trace_3625": {"8.9"},
    "cis_gcp_6_3_7_cloudsql_sqlserver_contained_auth": {"8.9"},
    "cis_gcp_6_4_cloudsql_ssl_required": {"8.24"},
    "cis_gcp_6_5_cloudsql_authorized_networks": {"8.20"},
    "cis_gcp_6_6_cloudsql_public_ip": {"8.20"},
    "cis_gcp_6_7_cloudsql_backups": {"8.13"},
    "cis_gcp_7_1_bigquery_dataset_public": {"8.3"},
    "cis_gcp_7_2_bigquery_table_cmek": {"8.24"},
    "cis_gcp_7_3_bigquery_dataset_cmek": {"8.24"},
    "cis_gw_1_1_1_super_admin_count_too_low": {"8.2"},
    "cis_gw_1_1_2_super_admin_count_too_high": {"5.18", "8.2"},
    "cis_gw_1_1_3_super_admin_used_for_daily_admin": {"8.2"},
    "cis_gw_4_1_1_1_admin_2sv_not_enforced": {"8.5", "8.2"},
    "cis_gw_4_1_1_3_user_2sv_not_enforced": {"8.5"},
    "cloud_security_product_deactivated": {"8.16"},
    "compute_instance_exposed": {"8.20"},
    "database_instance_exposed": {"8.20"},
    "delegation_boundary_modifiable": {"5.18", "8.2"},
    "device_security_posture_gaps": {"8.1", "8.8", "8.9"},
    "eol_software": {"8.8"},
    "identity_administration_privileges": {"5.18", "8.2"},
    "identity_mfa_gaps": {"8.5"},
    "inactive-user-active-accounts": {"5.18"},
    "malicious-npm-dependencies-shai-hulud": {"5.21", "8.8"},
    "mfa-missing": {"8.5"},
    "object_storage_public": {"8.3"},
    "policy_administration_privileges": {"5.18", "8.2"},
    "tailscale_tailnet_approval_disabled": {"5.15"},
    "tailscale_network_flow_logging_disabled": {"8.15"},
    "tailscale_device_auto_updates_disabled": {"8.8"},
    "tailscale_device_key_expiry_disabled": {"5.17"},
    "unmanaged-account": {"5.16", "5.18"},
    "unpinned-github-actions": {"8.28", "8.32"},
    "workload_identity_admin_capabilities": {"5.18", "8.2"},
    "cis_k8s_5_1_1_cluster_admin_usage": {"5.18", "8.2"},
    "cis_k8s_5_1_2_secret_access": {"8.3"},
    "cis_k8s_5_1_3_wildcard_roles": {"5.18", "8.2"},
    "cis_k8s_5_1_4_pod_create_access": {"5.18"},
    "cis_k8s_5_1_5_default_sa_bindings": {"5.16", "5.18"},
    "cis_k8s_5_1_6_sa_token_mounts": {"5.17"},
    "cis_k8s_5_1_7_system_masters_group": {"8.2"},
    "cis_k8s_5_1_8_escalation_permissions": {"5.18", "8.2"},
    "cis_k8s_5_1_9_pv_create_access": {"5.18"},
    "cis_k8s_5_1_10_node_proxy_access": {"8.2"},
    "cis_k8s_5_1_11_csr_approval_access": {"8.5"},
    "cis_k8s_5_1_12_webhook_config_access": {"8.9"},
    "cis_k8s_5_1_13_sa_token_creation": {"5.17"},
    "cis_k8s_5_2_3_host_pid": {"8.9"},
    "cis_k8s_5_2_4_host_ipc": {"8.9"},
    "cis_k8s_5_2_5_host_network": {"8.9", "8.20"},
    "cis_k8s_5_2_6_allow_privilege_escalation": {"8.9"},
    "cis_k8s_5_2_11_host_path_volumes": {"8.9"},
    "cis_k8s_5_2_12_host_ports": {"8.9", "8.20"},
    "cis_k8s_5_4_1_secrets_in_env_vars": {"8.12"},
    "cis_k8s_5_6_2_runtime_default_seccomp": {"8.9"},
    "nist_ai_third_party_app_inventory": {"5.21", "5.23"},
    "nist_ai_third_party_app_sensitive_scopes": {"5.15", "8.3"},
    "nist_ai_admin_ai_app_authorizations": {"5.18", "8.2"},
    "nist_ai_aibom_agent_inventory": {"5.9", "5.21"},
    "nist_ai_aibom_coverage_gaps": {"5.9", "5.21"},
    "nist_ai_provider_api_key_hygiene": {"5.17", "5.18"},
}


def test_iso27001_mapped_rules_have_expected_requirements():
    for rule_id, expected_requirements in EXPECTED_ISO27001_REQUIREMENTS.items():
        rule = RULES[rule_id]
        actual_requirements = {
            fw.requirement
            for fw in rule.frameworks
            if fw.short_name == "27001" and fw.revision == "2022"
        }
        assert actual_requirements == expected_requirements
