from dataclasses import dataclass

from cartography.models.core.common import PropertyRef
from cartography.models.core.nodes import CartographyNodeProperties
from cartography.models.core.nodes import CartographyNodeSchema
from cartography.models.core.relationships import CartographyRelProperties
from cartography.models.core.relationships import CartographyRelSchema
from cartography.models.core.relationships import LinkDirection
from cartography.models.core.relationships import make_target_node_matcher
from cartography.models.core.relationships import OtherRelationships
from cartography.models.core.relationships import TargetNodeMatcher


@dataclass(frozen=True)
class MiradoreDeviceNodeProperties(CartographyNodeProperties):
    id: PropertyRef = PropertyRef(
        "id",
        description="Tenant-scoped identifier for the device, as `<site name>/<Miradore ID>`.",
    )
    lastupdated: PropertyRef = PropertyRef("lastupdated", set_in_kwargs=True)
    miradore_id: PropertyRef = PropertyRef(
        "miradore_id",
        extra_index=True,
        description="Raw Miradore ID of the device, which is only unique within the tenant.",
    )

    # Identity
    serial_number: PropertyRef = PropertyRef(
        "serial_number",
        extra_index=True,
        description="Device serial number.",
    )
    hostname: PropertyRef = PropertyRef(
        "hostname",
        extra_index=True,
        description="Device hostname as inventoried by Miradore.",
    )
    udid: PropertyRef = PropertyRef("udid", description="Device UDID.")
    imei: PropertyRef = PropertyRef("imei", description="Device IMEI.")
    android_id: PropertyRef = PropertyRef(
        "android_id",
        description="Android device identifier.",
    )
    mac_address: PropertyRef = PropertyRef(
        "mac_address",
        description="Primary MAC address.",
    )
    wifi_mac: PropertyRef = PropertyRef("wifi_mac", description="Wi-Fi MAC address.")
    bluetooth_mac: PropertyRef = PropertyRef(
        "bluetooth_mac",
        description="Bluetooth MAC address.",
    )
    ip_address: PropertyRef = PropertyRef(
        "ip_address",
        description="Public IP address last seen by Miradore.",
    )
    local_ip_address: PropertyRef = PropertyRef(
        "local_ip_address",
        description="Local IP address last reported by the device.",
    )

    # Hardware and operating system
    manufacturer: PropertyRef = PropertyRef(
        "manufacturer",
        description="Device manufacturer.",
    )
    model: PropertyRef = PropertyRef("model", description="Device model.")
    marketing_name: PropertyRef = PropertyRef(
        "marketing_name",
        description="Commercial model name.",
    )
    product_name: PropertyRef = PropertyRef(
        "product_name",
        description="Product name reported by the device.",
    )
    device_type: PropertyRef = PropertyRef(
        "device_type",
        description="Device type reported by the device.",
    )
    platform: PropertyRef = PropertyRef(
        "platform",
        description=(
            "Platform reported by Miradore: Android, iOS, WindowsPhone, "
            "WindowsDesktop, macOS, Other or Unknown."
        ),
    )
    os_platform: PropertyRef = PropertyRef(
        "os_platform",
        description="Operating system platform from the OS inventory.",
    )
    os_version: PropertyRef = PropertyRef(
        "os_version",
        description="Operating system version.",
    )
    os_build: PropertyRef = PropertyRef(
        "os_build",
        description="Operating system build.",
    )
    os_version_name: PropertyRef = PropertyRef(
        "os_version_name",
        description="Human readable operating system version name.",
    )
    os_language: PropertyRef = PropertyRef(
        "os_language",
        description="Operating system language.",
    )

    # Lifecycle
    status: PropertyRef = PropertyRef(
        "status",
        description=(
            "Device status: Active, AutoGenerated, Deleted, New, Suspended or Unmanaged."
        ),
    )
    online_status: PropertyRef = PropertyRef(
        "online_status",
        description=(
            "Connectivity status: Active, Inactive, Unavailable, Unknown or Unmanaged."
        ),
    )
    source: PropertyRef = PropertyRef(
        "source",
        description="Where the device record originated from.",
    )
    created: PropertyRef = PropertyRef(
        "created",
        description="Timestamp when the device was created in Miradore.",
    )
    modified: PropertyRef = PropertyRef(
        "modified",
        description="Timestamp when the device record was last modified.",
    )
    last_reported: PropertyRef = PropertyRef(
        "last_reported",
        description="Timestamp when the device last reported to Miradore.",
    )
    purchase_date: PropertyRef = PropertyRef(
        "purchase_date",
        description="Device purchase date.",
    )
    warranty_end_date: PropertyRef = PropertyRef(
        "warranty_end_date",
        description="Date the device warranty ends.",
    )
    lease_start_date: PropertyRef = PropertyRef(
        "lease_start_date",
        description="Date the device lease starts.",
    )
    lease_end_date: PropertyRef = PropertyRef(
        "lease_end_date",
        description="Date the device lease ends.",
    )

    # Miradore client
    client_id: PropertyRef = PropertyRef(
        "client_id",
        description="Miradore client ID installed on the device.",
    )
    client_version: PropertyRef = PropertyRef(
        "client_version",
        description="Miradore client version.",
    )
    client_build_number: PropertyRef = PropertyRef(
        "client_build_number",
        description="Miradore client build number.",
    )
    management_type: PropertyRef = PropertyRef(
        "management_type",
        description=(
            "How the device is managed, e.g. AndroidDeviceOwner, BuiltInMDM, "
            "iOSSupervised or WindowsClient."
        ),
    )
    device_owner_type: PropertyRef = PropertyRef(
        "device_owner_type",
        description="Ownership mode: Normal, ProfileOwner, DeviceOwner or WPoCOD.",
    )
    lost_mode_status: PropertyRef = PropertyRef(
        "lost_mode_status",
        description=(
            "Lost mode state: Disabled, Enabled or EnabledWithLocationTracking."
        ),
    )
    client_status: PropertyRef = PropertyRef(
        "client_status",
        description="Miradore client status reported for the device.",
    )

    # Cross-platform security posture
    passcode_set: PropertyRef = PropertyRef(
        "passcode_set",
        description="Whether a device passcode is set: No, Unknown or Yes.",
    )
    encryption_status: PropertyRef = PropertyRef(
        "encryption_status",
        description=(
            "Device encryption state: Activating, Disabled, Enabled, "
            "NotSupported or Unknown."
        ),
    )

    # iOS security posture
    ios_activation_lock: PropertyRef = PropertyRef(
        "ios_activation_lock",
        description="Whether iOS Activation Lock is enabled.",
    )
    ios_device_locator_service: PropertyRef = PropertyRef(
        "ios_device_locator_service",
        description="Whether the iOS device locator service is enabled.",
    )
    ios_hardware_encryption: PropertyRef = PropertyRef(
        "ios_hardware_encryption",
        description="iOS hardware encryption capability.",
    )
    ios_passcode_compliant: PropertyRef = PropertyRef(
        "ios_passcode_compliant",
        description="Whether the iOS passcode is compliant.",
    )
    ios_passcode_compliant_with_profiles: PropertyRef = PropertyRef(
        "ios_passcode_compliant_with_profiles",
        description="Whether the iOS passcode complies with the installed profiles.",
    )
    ios_passcode_present: PropertyRef = PropertyRef(
        "ios_passcode_present",
        description="Whether an iOS passcode is present: Unknown, No or Yes.",
    )
    ios_profile_jailbroken: PropertyRef = PropertyRef(
        "ios_profile_jailbroken",
        description="Whether the iOS profile indicates a jailbroken device.",
    )
    ios_software_jailbroken: PropertyRef = PropertyRef(
        "ios_software_jailbroken",
        description="Whether iOS software detection indicates a jailbroken device.",
    )
    ios_supervised: PropertyRef = PropertyRef(
        "ios_supervised",
        description="Whether the iOS device is supervised.",
    )

    # Android security posture
    android_rooted: PropertyRef = PropertyRef(
        "android_rooted",
        description="Android root state: Unknown, NotRooted or Rooted.",
    )
    android_passcode_sufficient: PropertyRef = PropertyRef(
        "android_passcode_sufficient",
        description="Whether the Android passcode is sufficient: Unknown, No or Yes.",
    )
    android_storage_encryption_required: PropertyRef = PropertyRef(
        "android_storage_encryption_required",
        description="Whether Android storage encryption is required.",
    )
    android_storage_encryption_status: PropertyRef = PropertyRef(
        "android_storage_encryption_status",
        description="Android storage encryption state.",
    )
    android_security_patch_level: PropertyRef = PropertyRef(
        "android_security_patch_level",
        description="Android security patch level.",
    )
    android_device_administration_enabled: PropertyRef = PropertyRef(
        "android_device_administration_enabled",
        description="Whether Android device administration is enabled.",
    )
    android_safe_status: PropertyRef = PropertyRef(
        "android_safe_status",
        description="Samsung SAFE/Knox status.",
    )
    android_password_complexity_requirement: PropertyRef = PropertyRef(
        "android_password_complexity_requirement",
        description="Required Android password complexity: None, Low, Medium or High.",
    )
    android_password_min_length: PropertyRef = PropertyRef(
        "android_password_min_length",
        description="Minimum required Android password length.",
    )
    android_password_quality_requirement: PropertyRef = PropertyRef(
        "android_password_quality_requirement",
        description="Required Android password quality.",
    )
    android_password_set: PropertyRef = PropertyRef(
        "android_password_set",
        description="Whether an Android password is set: Unknown, No or Yes.",
    )

    # macOS security posture
    macos_activation_lock_enabled: PropertyRef = PropertyRef(
        "macos_activation_lock_enabled",
        description="Whether macOS Activation Lock is enabled.",
    )

    # Windows security posture
    windows_secure_boot_state: PropertyRef = PropertyRef(
        "windows_secure_boot_state",
        description="Secure Boot state: NotSupported, Enabled or Disabled.",
    )
    windows_antivirus_status: PropertyRef = PropertyRef(
        "windows_antivirus_status",
        description="Windows antivirus status.",
    )
    windows_antivirus_signature_status: PropertyRef = PropertyRef(
        "windows_antivirus_signature_status",
        description="Whether antivirus signatures are up to date.",
    )
    windows_antispyware_status: PropertyRef = PropertyRef(
        "windows_antispyware_status",
        description="Windows antispyware status.",
    )
    windows_firewall_status: PropertyRef = PropertyRef(
        "windows_firewall_status",
        description="Windows firewall status.",
    )
    windows_user_account_control_status: PropertyRef = PropertyRef(
        "windows_user_account_control_status",
        description="User Account Control notification level.",
    )
    windows_tpm_specification_version: PropertyRef = PropertyRef(
        "windows_tpm_specification_version",
        description="Trusted Platform Module specification version.",
    )
    windows_complies_with_enterprise_encryption_policy: PropertyRef = PropertyRef(
        "windows_complies_with_enterprise_encryption_policy",
        description="Whether the device complies with the enterprise encryption policy.",
    )

    # Category, kept as properties rather than its own node
    category_id: PropertyRef = PropertyRef(
        "category_id",
        description="Miradore device category ID.",
    )
    category_name: PropertyRef = PropertyRef(
        "category_name",
        description="Miradore device category name.",
    )


@dataclass(frozen=True)
class MiradoreDeviceToTenantRelProperties(CartographyRelProperties):
    lastupdated: PropertyRef = PropertyRef("lastupdated", set_in_kwargs=True)


# (:MiradoreTenant)-[:RESOURCE]->(:MiradoreDevice)
@dataclass(frozen=True)
class MiradoreDeviceToTenantRel(CartographyRelSchema):
    """Links a Miradore tenant to one of its managed devices."""

    target_node_label: str = "MiradoreTenant"
    target_node_matcher: TargetNodeMatcher = make_target_node_matcher(
        {"id": PropertyRef("TENANT_ID", set_in_kwargs=True)},
    )
    direction: LinkDirection = LinkDirection.INWARD
    rel_label: str = "RESOURCE"
    properties: MiradoreDeviceToTenantRelProperties = (
        MiradoreDeviceToTenantRelProperties()
    )


@dataclass(frozen=True)
class MiradoreDeviceToUserRelProperties(CartographyRelProperties):
    lastupdated: PropertyRef = PropertyRef("lastupdated", set_in_kwargs=True)


# (:MiradoreUser)-[:OWNS]->(:MiradoreDevice)
@dataclass(frozen=True)
class MiradoreDeviceToUserRel(CartographyRelSchema):
    """Links a Miradore device to the user it is assigned to."""

    target_node_label: str = "MiradoreUser"
    target_node_matcher: TargetNodeMatcher = make_target_node_matcher(
        {"id": PropertyRef("user_id")},
    )
    direction: LinkDirection = LinkDirection.INWARD
    rel_label: str = "OWNS"
    properties: MiradoreDeviceToUserRelProperties = MiradoreDeviceToUserRelProperties()


@dataclass(frozen=True)
class MiradoreDeviceToOrganizationRelProperties(CartographyRelProperties):
    lastupdated: PropertyRef = PropertyRef("lastupdated", set_in_kwargs=True)


# (:MiradoreDevice)-[:MEMBER_OF]->(:MiradoreOrganization)
@dataclass(frozen=True)
class MiradoreDeviceToOrganizationRel(CartographyRelSchema):
    """Links a Miradore device to the organization it belongs to."""

    target_node_label: str = "MiradoreOrganization"
    target_node_matcher: TargetNodeMatcher = make_target_node_matcher(
        {"id": PropertyRef("organization_id")},
    )
    direction: LinkDirection = LinkDirection.OUTWARD
    rel_label: str = "MEMBER_OF"
    properties: MiradoreDeviceToOrganizationRelProperties = (
        MiradoreDeviceToOrganizationRelProperties()
    )


@dataclass(frozen=True)
class MiradoreDeviceToLocationRelProperties(CartographyRelProperties):
    lastupdated: PropertyRef = PropertyRef("lastupdated", set_in_kwargs=True)


# (:MiradoreDevice)-[:MEMBER_OF]->(:MiradoreLocation)
@dataclass(frozen=True)
class MiradoreDeviceToLocationRel(CartographyRelSchema):
    """Links a Miradore device to the location it is assigned to."""

    target_node_label: str = "MiradoreLocation"
    target_node_matcher: TargetNodeMatcher = make_target_node_matcher(
        {"id": PropertyRef("location_id")},
    )
    direction: LinkDirection = LinkDirection.OUTWARD
    rel_label: str = "MEMBER_OF"
    properties: MiradoreDeviceToLocationRelProperties = (
        MiradoreDeviceToLocationRelProperties()
    )


@dataclass(frozen=True)
class MiradoreDeviceToTagRelProperties(CartographyRelProperties):
    lastupdated: PropertyRef = PropertyRef("lastupdated", set_in_kwargs=True)


# (:MiradoreDevice)-[:TAGGED]->(:MiradoreTag)
@dataclass(frozen=True)
class MiradoreDeviceToTagRel(CartographyRelSchema):
    """Links a Miradore device to a tag assigned to it."""

    target_node_label: str = "MiradoreTag"
    target_node_matcher: TargetNodeMatcher = make_target_node_matcher(
        {"id": PropertyRef("tag_names", one_to_many=True)},
    )
    direction: LinkDirection = LinkDirection.OUTWARD
    rel_label: str = "TAGGED"
    properties: MiradoreDeviceToTagRelProperties = MiradoreDeviceToTagRelProperties()


@dataclass(frozen=True)
class MiradoreDeviceSchema(CartographyNodeSchema):
    """A device managed by Miradore, on any platform it supports."""

    label: str = "MiradoreDevice"
    properties: MiradoreDeviceNodeProperties = MiradoreDeviceNodeProperties()
    sub_resource_relationship: MiradoreDeviceToTenantRel = MiradoreDeviceToTenantRel()
    other_relationships: OtherRelationships = OtherRelationships(
        [
            MiradoreDeviceToUserRel(),
            MiradoreDeviceToOrganizationRel(),
            MiradoreDeviceToLocationRel(),
            MiradoreDeviceToTagRel(),
        ],
    )
