from dataclasses import dataclass

from cartography.models.core.common import PropertyRef
from cartography.models.core.nodes import CartographyNodeProperties
from cartography.models.core.nodes import CartographyNodeSchema
from cartography.models.core.nodes import ExtraNodeLabels
from cartography.models.core.relationships import CartographyRelProperties
from cartography.models.core.relationships import CartographyRelSchema
from cartography.models.core.relationships import LinkDirection
from cartography.models.core.relationships import make_target_node_matcher
from cartography.models.core.relationships import OtherRelationships
from cartography.models.core.relationships import TargetNodeMatcher
from cartography.models.ontology.labels import API_KEY


@dataclass(frozen=True)
class GCPServiceAccountKeyNodeProperties(CartographyNodeProperties):
    id: PropertyRef = PropertyRef(
        "id",
        extra_index=True,
        description="The full resource name of the key, e.g. `projects/{p}/serviceAccounts/{email}/keys/{key_id}`.",
    )
    name: PropertyRef = PropertyRef("name", description="Same as id.")
    key_type: PropertyRef = PropertyRef(
        "keyType",
        description="The provenance of the key. Always `USER_MANAGED` for ingested keys.",
    )
    key_origin: PropertyRef = PropertyRef(
        "keyOrigin",
        description="Whether the key was generated by Google (`GOOGLE_PROVIDED`) or imported (`USER_PROVIDED`).",
    )
    key_algorithm: PropertyRef = PropertyRef(
        "keyAlgorithm",
        description="The cryptographic algorithm of the key (e.g. `KEY_ALG_RSA_2048`).",
    )
    valid_after_time: PropertyRef = PropertyRef(
        "validAfterTime",
        description="RFC 3339 timestamp from which the key is valid (effectively the key creation time).",
    )
    valid_before_time: PropertyRef = PropertyRef(
        "validBeforeTime",
        description="RFC 3339 timestamp until which the key is valid.",
    )
    disabled: PropertyRef = PropertyRef(
        "disabled", description="Whether the key is disabled."
    )
    service_account_email: PropertyRef = PropertyRef(
        "serviceAccountEmail", description="Email of the parent GCPServiceAccount."
    )
    lastupdated: PropertyRef = PropertyRef("lastupdated", set_in_kwargs=True)


@dataclass(frozen=True)
class GCPServiceAccountKeyToProjectRelProperties(CartographyRelProperties):
    lastupdated: PropertyRef = PropertyRef("lastupdated", set_in_kwargs=True)


@dataclass(frozen=True)
class GCPServiceAccountKeyToProjectRel(CartographyRelSchema):
    target_node_label: str = "GCPProject"
    target_node_matcher: TargetNodeMatcher = make_target_node_matcher(
        {"id": PropertyRef("projectId", set_in_kwargs=True)},
    )
    direction: LinkDirection = LinkDirection.INWARD
    rel_label: str = "RESOURCE"
    properties: GCPServiceAccountKeyToProjectRelProperties = (
        GCPServiceAccountKeyToProjectRelProperties()
    )


@dataclass(frozen=True)
class GCPServiceAccountKeyToServiceAccountRelProperties(CartographyRelProperties):
    lastupdated: PropertyRef = PropertyRef("lastupdated", set_in_kwargs=True)


@dataclass(frozen=True)
# DEPRECATED: replaced by the canonical (:APIKey)-[:OWNED_BY]->(:ServiceAccount)
# edge (GCPServiceAccountKeyToServiceAccountOwnedByRel). Kept for backward
# compatibility, will be removed in v1.0.0.
# (:GCPServiceAccount)-[:HAS_KEY]->(:GCPServiceAccountKey)
class GCPServiceAccountKeyToServiceAccountRel(CartographyRelSchema):
    target_node_label: str = "GCPServiceAccount"
    target_node_matcher: TargetNodeMatcher = make_target_node_matcher(
        {"email": PropertyRef("serviceAccountEmail")},
    )
    direction: LinkDirection = LinkDirection.INWARD
    rel_label: str = "HAS_KEY"
    properties: GCPServiceAccountKeyToServiceAccountRelProperties = (
        GCPServiceAccountKeyToServiceAccountRelProperties()
    )


@dataclass(frozen=True)
# Canonical ontology edge: (:APIKey)-[:OWNED_BY]->(:ServiceAccount)
class GCPServiceAccountKeyToServiceAccountOwnedByRel(CartographyRelSchema):
    target_node_label: str = "GCPServiceAccount"
    target_node_matcher: TargetNodeMatcher = make_target_node_matcher(
        {"email": PropertyRef("serviceAccountEmail")},
    )
    direction: LinkDirection = LinkDirection.OUTWARD
    rel_label: str = "OWNED_BY"
    properties: GCPServiceAccountKeyToServiceAccountRelProperties = (
        GCPServiceAccountKeyToServiceAccountRelProperties()
    )


@dataclass(frozen=True)
class GCPServiceAccountKeySchema(CartographyNodeSchema):
    """Representation of a user-managed GCP [Service Account Key](https://cloud.google.com/iam/docs/reference/rest/v1/projects.serviceAccounts.keys). System-managed keys (rotated automatically by Google) are not ingested."""

    label: str = "GCPServiceAccountKey"
    # APIKey label is used for ontology mapping
    extra_node_labels: ExtraNodeLabels = ExtraNodeLabels([API_KEY])
    properties: GCPServiceAccountKeyNodeProperties = (
        GCPServiceAccountKeyNodeProperties()
    )
    sub_resource_relationship: GCPServiceAccountKeyToProjectRel = (
        GCPServiceAccountKeyToProjectRel()
    )
    other_relationships: OtherRelationships = OtherRelationships(
        [
            GCPServiceAccountKeyToServiceAccountRel(),
            GCPServiceAccountKeyToServiceAccountOwnedByRel(),
        ],
    )
