from dataclasses import dataclass

from cartography.models.core.common import PropertyRef
from cartography.models.core.nodes import CartographyNodeProperties
from cartography.models.core.nodes import CartographyNodeSchema
from cartography.models.core.nodes import ExtraNodeLabels
from cartography.models.core.relationships import CartographyRelProperties
from cartography.models.core.relationships import CartographyRelSchema
from cartography.models.core.relationships import LinkDirection
from cartography.models.core.relationships import make_target_node_matcher
from cartography.models.core.relationships import OtherRelationships
from cartography.models.core.relationships import TargetNodeMatcher
from cartography.models.ontology.labels import SECURITY_ISSUE


@dataclass(frozen=True)
class HuntressIncidentReportNodeProperties(CartographyNodeProperties):
    id: PropertyRef = PropertyRef(
        "id",
        description="Huntress-unique identifier for the incident report.",
    )
    lastupdated: PropertyRef = PropertyRef("lastupdated", set_in_kwargs=True)
    subject: PropertyRef = PropertyRef(
        "subject",
        description="Autogenerated one-line description of the incident.",
    )
    # `body` and `summary` are unbounded analyst prose. They are deliberately left out of
    # any index: Neo4j caps an indexed value at roughly 8 KB and rejects the write above it.
    body: PropertyRef = PropertyRef(
        "body",
        description="Autogenerated content describing the details of the incident.",
    )
    summary: PropertyRef = PropertyRef(
        "summary",
        description="Details of the incident report, as provided by a Huntress SOC analyst.",
    )
    severity: PropertyRef = PropertyRef(
        "severity",
        description="Incident report severity: `low`, `high` or `critical`.",
    )
    status: PropertyRef = PropertyRef(
        "status",
        description=(
            "Incident report status: `sent`, `closed`, `dismissed`, "
            "`auto_remediating`, `deleting` or `partner_dismissed`."
        ),
    )
    platform: PropertyRef = PropertyRef(
        "platform",
        description=(
            "Platform the incident was raised on: `windows`, `darwin`, `linux`, "
            "`microsoft_365`, `google`, `email_security` or `other`."
        ),
    )
    indicator_types: PropertyRef = PropertyRef(
        "indicator_types",
        description=(
            "Threat indicators found in the context of this incident report, such as "
            "`footholds`, `ransomware_canaries` or `process_detections`."
        ),
    )
    remediation_count: PropertyRef = PropertyRef(
        "remediation_count",
        description="Total number of remediations attached to the incident report.",
    )
    remediation_types: PropertyRef = PropertyRef(
        "remediation_types",
        description=(
            "Types of the first ten remediations attached to the incident report: "
            "`assisted`, `manual` or `containment`."
        ),
    )
    sent_at: PropertyRef = PropertyRef(
        "sent_at",
        description="Timestamp a Huntress SOC analyst notified the necessary parties.",
    )
    closed_at: PropertyRef = PropertyRef(
        "closed_at",
        description="Timestamp the incident report status was set to `closed`.",
    )
    status_updated_at: PropertyRef = PropertyRef(
        "status_updated_at",
        description="Timestamp the incident report status was last updated.",
    )
    updated_at: PropertyRef = PropertyRef(
        "updated_at",
        description="Timestamp the incident report was last updated.",
    )


@dataclass(frozen=True)
class HuntressIncidentReportToAccountRelProperties(CartographyRelProperties):
    lastupdated: PropertyRef = PropertyRef("lastupdated", set_in_kwargs=True)


# (:HuntressAccount)-[:RESOURCE]->(:HuntressIncidentReport)
@dataclass(frozen=True)
class HuntressIncidentReportToAccountRel(CartographyRelSchema):
    """Links a Huntress account to one of its incident reports."""

    target_node_label: str = "HuntressAccount"
    target_node_matcher: TargetNodeMatcher = make_target_node_matcher(
        {"id": PropertyRef("ACCOUNT_ID", set_in_kwargs=True)},
    )
    direction: LinkDirection = LinkDirection.INWARD
    rel_label: str = "RESOURCE"
    properties: HuntressIncidentReportToAccountRelProperties = (
        HuntressIncidentReportToAccountRelProperties()
    )


@dataclass(frozen=True)
class HuntressIncidentReportToOrganizationRelProperties(CartographyRelProperties):
    lastupdated: PropertyRef = PropertyRef("lastupdated", set_in_kwargs=True)


# (:HuntressIncidentReport)-[:MEMBER_OF]->(:HuntressOrganization)
@dataclass(frozen=True)
class HuntressIncidentReportToOrganizationRel(CartographyRelSchema):
    """Links a Huntress incident report to the organization it was raised for."""

    target_node_label: str = "HuntressOrganization"
    target_node_matcher: TargetNodeMatcher = make_target_node_matcher(
        {"id": PropertyRef("organization_id")},
    )
    direction: LinkDirection = LinkDirection.OUTWARD
    rel_label: str = "MEMBER_OF"
    properties: HuntressIncidentReportToOrganizationRelProperties = (
        HuntressIncidentReportToOrganizationRelProperties()
    )


@dataclass(frozen=True)
class HuntressIncidentReportToAgentRelProperties(CartographyRelProperties):
    lastupdated: PropertyRef = PropertyRef("lastupdated", set_in_kwargs=True)


# (:HuntressIncidentReport)-[:AFFECTS]->(:HuntressAgent)
@dataclass(frozen=True)
class HuntressIncidentReportToAgentRel(CartographyRelSchema):
    """Links a Huntress incident report to the agent that reported it."""

    target_node_label: str = "HuntressAgent"
    target_node_matcher: TargetNodeMatcher = make_target_node_matcher(
        {"id": PropertyRef("agent_id")},
    )
    direction: LinkDirection = LinkDirection.OUTWARD
    rel_label: str = "AFFECTS"
    properties: HuntressIncidentReportToAgentRelProperties = (
        HuntressIncidentReportToAgentRelProperties()
    )


@dataclass(frozen=True)
class HuntressIncidentReportSchema(CartographyNodeSchema):
    """An incident raised by the Huntress SOC against a protected endpoint or identity."""

    label: str = "HuntressIncidentReport"
    properties: HuntressIncidentReportNodeProperties = (
        HuntressIncidentReportNodeProperties()
    )
    extra_node_labels: ExtraNodeLabels = ExtraNodeLabels([SECURITY_ISSUE])
    sub_resource_relationship: HuntressIncidentReportToAccountRel = (
        HuntressIncidentReportToAccountRel()
    )
    other_relationships: OtherRelationships = OtherRelationships(
        [
            HuntressIncidentReportToOrganizationRel(),
            HuntressIncidentReportToAgentRel(),
        ],
    )
