from dataclasses import dataclass

from cartography.models.core.common import PropertyRef
from cartography.models.core.nodes import CartographyNodeProperties
from cartography.models.core.nodes import CartographyNodeSchema
from cartography.models.core.nodes import ExtraNodeLabels
from cartography.models.ontology.labels import TENANT


@dataclass(frozen=True)
class KeycloakRealmNodeProperties(CartographyNodeProperties):
    id: PropertyRef = PropertyRef(
        "id", description="The unique identifier of the realm"
    )
    # We need to index realm name as Keycloak use this slug instead of ID in all queries
    name: PropertyRef = PropertyRef(
        "realm", extra_index=True, description="The realm name (indexed for queries)"
    )
    display_name: PropertyRef = PropertyRef(
        "displayName", description="The display name of the realm"
    )
    enabled: PropertyRef = PropertyRef(
        "enabled", description="Whether the realm is enabled"
    )
    not_before: PropertyRef = PropertyRef(
        "notBefore", description="Not before timestamp for security"
    )
    default_signature_algorithm: PropertyRef = PropertyRef(
        "defaultSignatureAlgorithm",
        description="Default signature algorithm for the realm",
    )
    revoke_refresh_token: PropertyRef = PropertyRef(
        "revokeRefreshToken", description="Whether refresh tokens should be revoked"
    )
    refresh_token_max_reuse: PropertyRef = PropertyRef(
        "refreshTokenMaxReuse", description="Maximum reuse count for refresh tokens"
    )
    access_token_lifespan: PropertyRef = PropertyRef(
        "accessTokenLifespan", description="Lifespan of access tokens in seconds"
    )
    access_token_lifespan_for_implicit_flow: PropertyRef = PropertyRef(
        "accessTokenLifespanForImplicitFlow",
        description="Access token lifespan for implicit flow",
    )
    sso_session_idle_timeout: PropertyRef = PropertyRef(
        "ssoSessionIdleTimeout", description="SSO session idle timeout in seconds"
    )
    sso_session_max_lifespan: PropertyRef = PropertyRef(
        "ssoSessionMaxLifespan", description="Maximum SSO session lifespan in seconds"
    )
    sso_session_idle_timeout_remember_me: PropertyRef = PropertyRef(
        "ssoSessionIdleTimeoutRememberMe",
        description="SSO session idle timeout when remember me is enabled",
    )
    sso_session_max_lifespan_remember_me: PropertyRef = PropertyRef(
        "ssoSessionMaxLifespanRememberMe",
        description="Maximum SSO session lifespan when remember me is enabled",
    )
    offline_session_idle_timeout: PropertyRef = PropertyRef(
        "offlineSessionIdleTimeout",
        description="Offline session idle timeout in seconds",
    )
    offline_session_max_lifespan_enabled: PropertyRef = PropertyRef(
        "offlineSessionMaxLifespanEnabled",
        description="Whether offline session max lifespan is enabled",
    )
    offline_session_max_lifespan: PropertyRef = PropertyRef(
        "offlineSessionMaxLifespan",
        description="Maximum offline session lifespan in seconds",
    )
    client_session_idle_timeout: PropertyRef = PropertyRef(
        "clientSessionIdleTimeout", description="Client session idle timeout in seconds"
    )
    client_session_max_lifespan: PropertyRef = PropertyRef(
        "clientSessionMaxLifespan",
        description="Maximum client session lifespan in seconds",
    )
    client_offline_session_idle_timeout: PropertyRef = PropertyRef(
        "clientOfflineSessionIdleTimeout",
        description="Client offline session idle timeout in seconds",
    )
    client_offline_session_max_lifespan: PropertyRef = PropertyRef(
        "clientOfflineSessionMaxLifespan",
        description="Maximum client offline session lifespan in seconds",
    )
    access_code_lifespan: PropertyRef = PropertyRef(
        "accessCodeLifespan", description="Access code lifespan in seconds"
    )
    access_code_lifespan_user_action: PropertyRef = PropertyRef(
        "accessCodeLifespanUserAction",
        description="Access code lifespan for user actions in seconds",
    )
    access_code_lifespan_login: PropertyRef = PropertyRef(
        "accessCodeLifespanLogin",
        description="Access code lifespan for login in seconds",
    )
    action_token_generated_by_admin_lifespan: PropertyRef = PropertyRef(
        "actionTokenGeneratedByAdminLifespan",
        description="Action token lifespan when generated by admin",
    )
    action_token_generated_by_user_lifespan: PropertyRef = PropertyRef(
        "actionTokenGeneratedByUserLifespan",
        description="Action token lifespan when generated by user",
    )
    oauth2_device_code_lifespan: PropertyRef = PropertyRef(
        "oauth2DeviceCodeLifespan", description="OAuth2 device code lifespan in seconds"
    )
    oauth2_device_polling_interval: PropertyRef = PropertyRef(
        "oauth2DevicePollingInterval",
        description="OAuth2 device polling interval in seconds",
    )
    ssl_required: PropertyRef = PropertyRef(
        "sslRequired", description="SSL requirement level for the realm"
    )
    password_credential_grant_allowed: PropertyRef = PropertyRef(
        "passwordCredentialGrantAllowed",
        description="Whether password credential grant is allowed",
    )
    registration_allowed: PropertyRef = PropertyRef(
        "registrationAllowed", description="Whether user registration is allowed"
    )
    registration_email_as_username: PropertyRef = PropertyRef(
        "registrationEmailAsUsername",
        description="Whether email is used as username during registration",
    )
    remember_me: PropertyRef = PropertyRef(
        "rememberMe", description="Whether remember me functionality is enabled"
    )
    verify_email: PropertyRef = PropertyRef(
        "verifyEmail", description="Whether email verification is required"
    )
    login_with_email_allowed: PropertyRef = PropertyRef(
        "loginWithEmailAllowed", description="Whether login with email is allowed"
    )
    duplicate_emails_allowed: PropertyRef = PropertyRef(
        "duplicateEmailsAllowed", description="Whether duplicate emails are allowed"
    )
    reset_password_allowed: PropertyRef = PropertyRef(
        "resetPasswordAllowed", description="Whether password reset is allowed"
    )
    edit_username_allowed: PropertyRef = PropertyRef(
        "editUsernameAllowed", description="Whether username editing is allowed"
    )
    user_cache_enabled: PropertyRef = PropertyRef(
        "userCacheEnabled", description="Whether user cache is enabled"
    )
    realm_cache_enabled: PropertyRef = PropertyRef(
        "realmCacheEnabled", description="Whether realm cache is enabled"
    )
    brute_force_protected: PropertyRef = PropertyRef(
        "bruteForceProtected", description="Whether brute force protection is enabled"
    )
    permanent_lockout: PropertyRef = PropertyRef(
        "permanentLockout", description="Whether permanent lockout is enabled"
    )
    max_temporary_lockouts: PropertyRef = PropertyRef(
        "maxTemporaryLockouts", description="Maximum number of temporary lockouts"
    )
    max_failure_wait_seconds: PropertyRef = PropertyRef(
        "maxFailureWaitSeconds", description="Maximum failure wait time in seconds"
    )
    minimum_quick_login_wait_seconds: PropertyRef = PropertyRef(
        "minimumQuickLoginWaitSeconds",
        description="Minimum quick login wait time in seconds",
    )
    wait_increment_seconds: PropertyRef = PropertyRef(
        "waitIncrementSeconds", description="Wait increment in seconds"
    )
    quick_login_check_milli_seconds: PropertyRef = PropertyRef(
        "quickLoginCheckMilliSeconds",
        description="Quick login check time in milliseconds",
    )
    max_delta_time_seconds: PropertyRef = PropertyRef(
        "maxDeltaTimeSeconds", description="Maximum delta time in seconds"
    )
    failure_factor: PropertyRef = PropertyRef(
        "failureFactor", description="Failure factor for brute force protection"
    )
    events_enabled: PropertyRef = PropertyRef(
        "eventsEnabled", description="Whether events are enabled"
    )
    events_expiration: PropertyRef = PropertyRef(
        "eventsExpiration", description="Events expiration time"
    )
    admin_events_enabled: PropertyRef = PropertyRef(
        "adminEventsEnabled", description="Whether admin events are enabled"
    )
    admin_events_details_enabled: PropertyRef = PropertyRef(
        "adminEventsDetailsEnabled",
        description="Whether admin event details are enabled",
    )
    internationalization_enabled: PropertyRef = PropertyRef(
        "internationalizationEnabled",
        description="Whether internationalization is enabled",
    )
    default_locale: PropertyRef = PropertyRef(
        "defaultLocale", description="Default locale for the realm"
    )
    password_policy: PropertyRef = PropertyRef(
        "passwordPolicy", description="Password policy configuration"
    )
    otp_policy_type: PropertyRef = PropertyRef(
        "otpPolicyType", description="OTP policy type"
    )
    otp_policy_algorithm: PropertyRef = PropertyRef(
        "otpPolicyAlgorithm", description="OTP policy algorithm"
    )
    otp_policy_initial_counter: PropertyRef = PropertyRef(
        "otpPolicyInitialCounter", description="OTP policy initial counter"
    )
    otp_policy_digits: PropertyRef = PropertyRef(
        "otpPolicyDigits", description="Number of digits in OTP"
    )
    otp_policy_look_ahead_window: PropertyRef = PropertyRef(
        "otpPolicyLookAheadWindow", description="OTP policy look ahead window"
    )
    otp_policy_period: PropertyRef = PropertyRef(
        "otpPolicyPeriod", description="OTP policy period"
    )
    otp_policy_code_reusable: PropertyRef = PropertyRef(
        "otpPolicyCodeReusable", description="Whether OTP codes are reusable"
    )
    web_authn_policy_rp_entity_name: PropertyRef = PropertyRef(
        "webAuthnPolicyRpEntityName", description="WebAuthn relying party entity name"
    )
    web_authn_policy_rp_id: PropertyRef = PropertyRef(
        "webAuthnPolicyRpId", description="WebAuthn relying party ID"
    )
    web_authn_policy_attestation_conveyance_preference: PropertyRef = PropertyRef(
        "webAuthnPolicyAttestationConveyancePreference",
        description="WebAuthn attestation conveyance preference",
    )
    web_authn_policy_authenticator_attachment: PropertyRef = PropertyRef(
        "webAuthnPolicyAuthenticatorAttachment",
        description="WebAuthn authenticator attachment",
    )
    web_authn_policy_require_resident_key: PropertyRef = PropertyRef(
        "webAuthnPolicyRequireResidentKey",
        description="Whether WebAuthn requires resident key",
    )
    web_authn_policy_user_verification_requirement: PropertyRef = PropertyRef(
        "webAuthnPolicyUserVerificationRequirement",
        description="WebAuthn user verification requirement",
    )
    web_authn_policy_create_timeout: PropertyRef = PropertyRef(
        "webAuthnPolicyCreateTimeout", description="WebAuthn create timeout"
    )
    web_authn_policy_avoid_same_authenticator_register: PropertyRef = PropertyRef(
        "webAuthnPolicyAvoidSameAuthenticatorRegister",
        description="Whether to avoid same authenticator registration",
    )
    web_authn_policy_passwordless_rp_entity_name: PropertyRef = PropertyRef(
        "webAuthnPolicyPasswordlessRpEntityName",
        description="WebAuthn passwordless relying party entity name",
    )
    web_authn_policy_passwordless_rp_id: PropertyRef = PropertyRef(
        "webAuthnPolicyPasswordlessRpId",
        description="WebAuthn passwordless relying party ID",
    )
    web_authn_policy_passwordless_attestation_conveyance_preference: PropertyRef = (
        PropertyRef(
            "webAuthnPolicyPasswordlessAttestationConveyancePreference",
            description="WebAuthn passwordless attestation conveyance preference",
        )
    )
    web_authn_policy_passwordless_authenticator_attachment: PropertyRef = PropertyRef(
        "webAuthnPolicyPasswordlessAuthenticatorAttachment",
        description="WebAuthn passwordless authenticator attachment",
    )
    web_authn_policy_passwordless_require_resident_key: PropertyRef = PropertyRef(
        "webAuthnPolicyPasswordlessRequireResidentKey",
        description="Whether WebAuthn passwordless requires resident key",
    )
    web_authn_policy_passwordless_user_verification_requirement: PropertyRef = (
        PropertyRef(
            "webAuthnPolicyPasswordlessUserVerificationRequirement",
            description="WebAuthn passwordless user verification requirement",
        )
    )
    web_authn_policy_passwordless_create_timeout: PropertyRef = PropertyRef(
        "webAuthnPolicyPasswordlessCreateTimeout",
        description="WebAuthn passwordless create timeout",
    )
    web_authn_policy_passwordless_avoid_same_authenticator_register: PropertyRef = (
        PropertyRef(
            "webAuthnPolicyPasswordlessAvoidSameAuthenticatorRegister",
            description="Whether to avoid same authenticator registration for passwordless",
        )
    )
    keycloak_version: PropertyRef = PropertyRef(
        "keycloakVersion", description="Version of Keycloak"
    )
    user_managed_access_allowed: PropertyRef = PropertyRef(
        "userManagedAccessAllowed", description="Whether user managed access is allowed"
    )
    organizations_enabled: PropertyRef = PropertyRef(
        "organizationsEnabled", description="Whether organizations are enabled"
    )
    verifiable_credentials_enabled: PropertyRef = PropertyRef(
        "verifiableCredentialsEnabled",
        description="Whether verifiable credentials are enabled",
    )
    admin_permissions_enabled: PropertyRef = PropertyRef(
        "adminPermissionsEnabled", description="Whether admin permissions are enabled"
    )
    social: PropertyRef = PropertyRef(
        "social", description="Social login configuration"
    )
    update_profile_on_initial_social_login: PropertyRef = PropertyRef(
        "updateProfileOnInitialSocialLogin",
        description="Whether to update profile on initial social login",
    )
    o_auth2_device_code_lifespan: PropertyRef = PropertyRef(
        "oAuth2DeviceCodeLifespan", description="OAuth2 device code lifespan"
    )
    o_auth2_device_polling_interval: PropertyRef = PropertyRef(
        "oAuth2DevicePollingInterval", description="OAuth2 device polling interval"
    )
    bruteForceStrategy: PropertyRef = PropertyRef(
        "bruteForceStrategy", description="Brute force protection strategy"
    )
    default_role_id: PropertyRef = PropertyRef(
        "defaultRole.id", description="ID of the default role"
    )
    lastupdated: PropertyRef = PropertyRef("LASTUPDATED", set_in_kwargs=True)


@dataclass(frozen=True)
class KeycloakRealmSchema(CartographyNodeSchema):
    """Represents a Keycloak realm, which is a security domain where users, groups, roles, and other entities are managed."""

    label: str = "KeycloakRealm"
    properties: KeycloakRealmNodeProperties = KeycloakRealmNodeProperties()
    extra_node_labels: ExtraNodeLabels = ExtraNodeLabels([TENANT])
