import inspect
import re
from pathlib import Path

import cartography.models.aibom as aibom_models
import cartography.models.crowdstrike as crowdstrike_models
import cartography.models.gitlab as gitlab_models
import cartography.models.gsuite as gsuite_models
import cartography.models.lastpass as lastpass_models
from cartography.models.core.relationships import LinkDirection
from cartography.models.introspection import DataModel
from cartography.models.introspection import inspect_data_model
from cartography.models.introspection import Node
from cartography.models.introspection import PermissionRelationshipDefinition
from cartography.models.introspection import Relationship
from cartography.models.schema_docs import _module_title
from cartography.models.schema_docs import GENERATED_NOTICE
from cartography.models.schema_docs import generated_schema_modules
from cartography.models.schema_docs import MANUAL_SCHEMA_MODULES
from cartography.models.schema_docs import REDIRECT_SCHEMA_MODULES
from cartography.models.schema_docs import render_module_schema
from cartography.models.schema_docs import write_schema_docs

REPOSITORY_ROOT = Path(__file__).resolve().parents[4]


def test_documentation_schema_links_target_generated_headings():
    model = inspect_data_model()
    schema_link_pattern = re.compile(
        r"modules/(?P<module>[^/]+)/schema\.html#(?P<anchor>[a-z0-9_-]+)",
    )
    generated_anchors_by_module: dict[str, set[str]] = {}
    invalid_links: list[str] = []

    for path in (REPOSITORY_ROOT / "docs" / "root").rglob("*.md"):
        for match in schema_link_pattern.finditer(path.read_text()):
            module = match.group("module")
            if module not in generated_anchors_by_module:
                generated = render_module_schema(model, module)
                generated_anchors_by_module[module] = {
                    heading.lower()
                    for heading in re.findall(
                        r"^### ([A-Za-z0-9_-]+)$", generated, re.MULTILINE
                    )
                }
            if match.group("anchor") not in generated_anchors_by_module[module]:
                invalid_links.append(f"{path}: {match.group(0)}")

    assert invalid_links == []


def test_relationship_docstrings_are_user_facing_descriptions():
    # Arrange
    model = inspect_data_model()
    relationship_schema_types = {
        type(schema)
        for relationship in model.relationships
        for schema in relationship.schemas
    }
    forbidden_markers = (
        "(:",
        "```",
        "one_to_many",
        "other_relationships",
        "target_node_matcher",
        "source_node_matcher",
        "matchlink:",
        "loaded as",
        "lifecycle follows",
    )

    # Act
    violations = []
    for schema_type in sorted(
        relationship_schema_types,
        key=lambda item: (item.__module__, item.__name__),
    ):
        raw_docstring = schema_type.__doc__
        if not raw_docstring or raw_docstring.lstrip().startswith(
            f"{schema_type.__name__}(",
        ):
            continue
        docstring = inspect.cleandoc(raw_docstring)
        matched_markers = tuple(
            marker
            for marker in forbidden_markers
            if marker.casefold() in docstring.casefold()
        )
        if matched_markers:
            violations.append(
                f"{schema_type.__module__}.{schema_type.__name__}: "
                f"{', '.join(matched_markers)}",
            )

    # Assert
    assert not violations, "\n".join(violations)


def test_typed_analysis_jobs_are_rendered_from_introspected_model():
    # Arrange
    model = inspect_data_model(gsuite_models)

    # Act
    generated = render_module_schema(model, "gsuite")

    # Assert
    assert (
        "`(:Human)-[:IDENTITY_GSUITE]->(:GSuiteUser)`: generated by analysis job "
        "`GSuite user map to Human`."
    ) in generated


def test_undirected_analysis_relationships_are_rendered_without_arrows():
    # Arrange
    node = Node(
        label="AWSEC2KeyPair",
        descriptions=(),
        extra_labels=(),
        conditional_labels=(),
        properties=(),
        modules=("aws",),
        schemas=(),
    )
    relationship = Relationship(
        source_label="AWSEC2KeyPair",
        label="MATCHING_FINGERPRINT",
        target_label="AWSEC2KeyPair",
        direction=None,
        descriptions=(),
        properties=(),
        modules=("aws",),
        origins=("analysis",),
        schemas=(),
        analysis_jobs=(),
    )
    model = DataModel(nodes=(node,), relationships=(relationship,))

    # Act
    generated = render_module_schema(model, "aws")

    # Assert
    assert "AWSEC2KeyPair ---|MATCHING_FINGERPRINT| AWSEC2KeyPair" in generated
    assert "(:AWSEC2KeyPair)-[:MATCHING_FINGERPRINT]-(:AWSEC2KeyPair)" in generated
    assert "Source:" not in generated


def test_permission_evaluation_relationships_render_permissions_without_source():
    # Arrange
    definition = PermissionRelationshipDefinition(
        provider="aws",
        source_label="AWSPrincipal",
        target_label="AWSS3Bucket",
        relationship_name="CAN_READ",
        permissions=("S3:GetObject",),
        config_path="cartography/data/permission_relationships.yaml",
    )
    node = Node(
        label="AWSS3Bucket",
        descriptions=(),
        extra_labels=(),
        conditional_labels=(),
        properties=(),
        modules=("aws",),
        schemas=(),
    )
    relationship = Relationship(
        source_label="AWSPrincipal",
        label="CAN_READ",
        target_label="AWSS3Bucket",
        direction=LinkDirection.OUTWARD,
        descriptions=("Allows an AWS principal to read objects from an S3 bucket.",),
        properties=(),
        modules=("aws",),
        origins=("permission_evaluation",),
        schemas=(),
        analysis_jobs=(),
        permission_relationships=(definition,),
    )
    model = DataModel(
        nodes=(node,),
        relationships=(relationship,),
        permission_relationships=(definition,),
    )

    # Act
    generated = render_module_schema(model, "aws")

    # Assert
    assert "Allows an AWS principal to read objects from an S3 bucket." in generated
    assert "(:AWSPrincipal)-[:CAN_READ]->(:AWSS3Bucket)" in generated
    assert "Source:" not in generated
    assert "Evaluated permissions: `S3:GetObject`" in generated


def test_ontology_and_cross_module_relationships_are_duplicated_in_module_docs():
    # Arrange
    node = Node(
        label="LastpassUser",
        descriptions=(),
        extra_labels=("UserAccount",),
        conditional_labels=(),
        properties=(),
        modules=("lastpass",),
        schemas=(),
        ontology_labels=("UserAccount",),
    )
    # The canonical User node is what lets a provider page document HAS_ACCOUNT even
    # though the provider never declares that edge.
    canonical_user = Node(
        label="User",
        descriptions=(),
        extra_labels=(),
        conditional_labels=(),
        properties=(),
        modules=("ontology",),
        schemas=(),
    )
    relationships = (
        Relationship(
            source_label="User",
            label="HAS_ACCOUNT",
            target_label="UserAccount",
            direction=LinkDirection.OUTWARD,
            descriptions=(),
            properties=(),
            modules=("ontology",),
            origins=("node_schema",),
            schemas=(),
            analysis_jobs=(),
        ),
        Relationship(
            source_label="Human",
            label="IDENTITY_LASTPASS",
            target_label="LastpassUser",
            direction=LinkDirection.OUTWARD,
            descriptions=(),
            properties=(),
            modules=("analysis",),
            origins=("analysis",),
            schemas=(),
            analysis_jobs=(),
        ),
    )
    model = DataModel(nodes=(node, canonical_user), relationships=relationships)

    # Act
    generated = render_module_schema(model, "lastpass")

    # Assert
    # Inherited ontology edges keep the far endpoint semantic when possible, but
    # rewrite the near endpoint to the concrete node being documented.
    assert "(:User)-[:HAS_ACCOUNT]->(:LastpassUser)" in generated
    assert "(:Human)-[:IDENTITY_LASTPASS]->(:LastpassUser)" in generated


def test_only_legacy_modules_keep_a_hand_written_schema_page():
    # Arrange
    modules_root = REPOSITORY_ROOT / "docs" / "root" / "modules"

    # Act
    hand_written = {path.parent.name for path in modules_root.glob("*/schema.md")}

    # Assert
    assert hand_written == set(MANUAL_SCHEMA_MODULES) | set(REDIRECT_SCHEMA_MODULES)


def test_every_generated_module_renders_documented_content():
    """Covers the exact module list the Sphinx build renders, which is not run in CI."""
    # Arrange
    model = inspect_data_model()
    modules = generated_schema_modules(model)

    # Act
    pages = {module: render_module_schema(model, module) for module in modules}

    # Assert
    assert set(modules).isdisjoint(MANUAL_SCHEMA_MODULES)
    assert len(modules) > 40
    for module, page in pages.items():
        node_headings = [
            line.removeprefix("### ")
            for line in page.splitlines()
            if line.startswith("### ")
        ]
        assert page.startswith(GENERATED_NOTICE), module
        assert node_headings, module
        assert node_headings == sorted(node_headings, key=str.casefold), module
        assert "No description provided." not in page, module


def test_write_schema_docs_overwrites_every_generated_page(tmp_path: Path):
    # Arrange
    model = inspect_data_model(lastpass_models)
    output_path = tmp_path / "lastpass" / "schema.md"
    output_path.parent.mkdir(parents=True)
    output_path.write_text("Stale content\n")

    # Act
    write_schema_docs(model, tmp_path)

    # Assert
    assert output_path.read_text() == render_module_schema(model, "lastpass")


def test_module_titles_use_display_overrides():
    # Arrange
    expected = {
        "aibom": "AIBOM",
        "aws": "AWS",
        "gcp": "GCP",
        "oci": "OCI",
        "sentinelone": "SentinelOne",
        "socketdev": "Socket.dev",
        "docker_scout": "Docker Scout",
    }

    # Act
    actual = {module: _module_title(module) for module in expected}

    # Assert
    assert actual == expected


def test_node_sections_follow_a_stable_layout():
    # Arrange
    model = inspect_data_model(aibom_models)

    # Act
    generated = render_module_schema(model, "aibom")

    # Assert
    assert generated.startswith(GENERATED_NOTICE)
    assert "## AIBOM Schema" in generated
    assert generated.count("#### Properties") == len(model.nodes)
    assert (
        generated.index("#### Properties")
        < generated.index("| Field | Index | Description |")
        < generated.index("#### Relationships")
    )


def test_conditional_labels_render_their_condition_and_ontology_link():
    # Arrange
    model = inspect_data_model(aibom_models)

    # Act
    generated = render_module_schema(model, "aibom")

    # Assert
    assert "`AIAgent` when `category` equals `agent`." in generated
    assert (
        "[`AIModel`](#ontology-aimodel) (ontology label) "
        "when `category` equals `model`." in generated
    )


def test_ontology_properties_are_italicised_and_described():
    # Arrange
    model = inspect_data_model(aibom_models)

    # Act
    generated = render_module_schema(model, "aibom")

    # Assert
    assert "Ontology-generated fields are shown in *italics*." in generated
    assert (
        "| *_ont_source* |  | Module that populated this node's ontology fields. |"
        in generated
    )


def test_compatibility_labels_are_flagged_with_their_replacement():
    # Arrange
    model = inspect_data_model(crowdstrike_models)

    # Act
    generated = render_module_schema(model, "crowdstrike")

    # Assert
    assert "> **Additional Label Definitions**:" in generated
    assert (
        "> - `SpotlightVulnerability`: Compatibility label for the deprecated "
        "`SpotlightVulnerability` crowdstrike node label. Use "
        "`CrowdstrikeSpotlightVulnerability` instead. Scheduled for removal in v1.0.0."
        in generated
    )


def test_mermaid_diagram_only_covers_intra_module_edges():
    # Arrange
    model = inspect_data_model(gitlab_models)

    # Act
    generated = render_module_schema(model, "gitlab")
    mermaid = generated.split("graph LR", 1)[1].split("```", 1)[0]

    # Assert
    assert "GitLabProject -- HAS_ENVIRONMENT --> GitLabEnvironment" in mermaid
    module_labels = {node.label for node in model.nodes}
    for line in mermaid.splitlines():
        if not line.strip():
            continue
        endpoints = line.split("--")[0].strip(), line.split(">")[-1].strip()
        assert all(endpoint in module_labels for endpoint in endpoints), line


def test_relationship_property_tables_hide_internal_fields():
    # Arrange
    model = inspect_data_model(gitlab_models)

    # Act
    generated = render_module_schema(model, "gitlab")

    # Assert
    blocks = [
        block.split("\n\n", 1)[0]
        for block in generated.split("  - Properties:\n\n")[1:]
    ]
    assert blocks, "gitlab documents at least one relationship property table"
    # firstseen, lastupdated and _-prefixed bookkeeping fields carry no meaning here.
    for block in blocks:
        assert "| firstseen |" not in block
        assert "| lastupdated |" not in block
        assert "| _" not in block
    assert "linked_variable_ids" not in generated


def test_each_relationship_is_documented_once_per_node_section():
    # Arrange
    model = inspect_data_model(gitlab_models)

    # Act
    generated = render_module_schema(model, "gitlab")
    section = generated.split("### GitLabEnvironment", 1)[1].split("\n### ", 1)[0]

    # Assert
    assert (
        section.count("(:GitLabProject)-[:HAS_ENVIRONMENT]->(:GitLabEnvironment)") == 1
    )


def test_concrete_nodes_render_inherited_ontology_relationships():
    model = inspect_data_model()

    for module, label in (
        ("aws", "AWSECSContainer"),
        ("kubernetes", "KubernetesContainer"),
        ("railway", "RailwayDeployment"),
    ):
        generated = render_module_schema(model, module)
        section = generated.split(f"### {label}", 1)[1].split("\n### ", 1)[0]

        assert f"`(:{label})-[:RESOLVED_IMAGE]->(:Image)`" in section
        assert "`(:Container)-[:RESOLVED_IMAGE]->(:Image)`" not in section
        # Validation-only Container→FilesystemSnapshot must not appear; a
        # provider-native SCANNED_AS to a concrete snapshot label is fine.
        assert f"`(:{label})-[:SCANNED_AS]->(:FilesystemSnapshot)`" not in section


def test_ontology_schema_documents_constraint_vs_expected_edges():
    model = inspect_data_model()

    generated = render_module_schema(model, "ontology")

    assert "not inherited onto concrete node schemas" in generated
    assert "Expected (materialized) ontology edges" in generated
