from dataclasses import dataclass

from cartography.models.core.common import PropertyRef
from cartography.models.core.nodes import CartographyNodeProperties
from cartography.models.core.nodes import CartographyNodeSchema
from cartography.models.core.relationships import CartographyRelProperties
from cartography.models.core.relationships import CartographyRelSchema
from cartography.models.core.relationships import LinkDirection
from cartography.models.core.relationships import make_target_node_matcher
from cartography.models.core.relationships import TargetNodeMatcher


@dataclass(frozen=True)
class TailscalePostureIntegrationNodeProperties(CartographyNodeProperties):
    id: PropertyRef = PropertyRef(
        "id",
        description="A unique identifier for the integration (generated by the system).",
    )
    lastupdated: PropertyRef = PropertyRef("lastupdated", set_in_kwargs=True)
    provider: PropertyRef = PropertyRef(
        "provider",
        description="The device posture provider. Required on POST requests, ignored on PATCH requests.",
    )
    cloud_id: PropertyRef = PropertyRef(
        "cloudId",
        description="Identifies which of the provider's clouds to integrate with. - For CrowdStrike Falcon, it will be one of `us-1`, `us-2`, `eu-1` or `us-gov`. - For Microsoft Intune, it will be one of `global` or `us-gov`. - For Jamf Pro, Kandji and Sentinel One, it is the FQDN of your subdomain, for example `mydomain.sentinelone.net`. - For Kolide, this is left blank.",
    )
    client_id: PropertyRef = PropertyRef(
        "clientId",
        description="Unique identifier for your client. - For Microsoft Intune, it will be your application's UUID. - For CrowdStrike Falcon and Jamf Pro, it will be your client id. - For Kandji, Kolide and Sentinel One, this is left blank.",
    )
    tenant_id: PropertyRef = PropertyRef(
        "tenantId",
        description="The Microsoft Intune directory (tenant) ID. For other providers, this is left blank.",
    )
    config_updated: PropertyRef = PropertyRef(
        "configUpdated",
        description="Timestamp of the last time this configuration was updated, in RFC 3339 format.",
    )
    status_last_sync: PropertyRef = PropertyRef(
        "status.lastSync",
        description="Timestamp of the last synchronization with the device posture provider, in RFC 3339 format.",
    )
    status_error: PropertyRef = PropertyRef(
        "status.error",
        description="If the last synchronization failed, this shows the error message associated with the failed synchronization.",
    )
    status_provider_host_count: PropertyRef = PropertyRef(
        "status.providerHostCount",
        description="The number of devices known to the provider.",
    )
    status_matched_count: PropertyRef = PropertyRef(
        "status.matchedCount",
        description="The number of Tailscale nodes that were matched with provider.",
    )
    status_possible_matched_count: PropertyRef = PropertyRef(
        "status.possibleMatchedCount",
        description="The number of Tailscale nodes with identifiers for matching.",
    )


@dataclass(frozen=True)
class TailscalePostureIntegrationToTailnetRelProperties(CartographyRelProperties):
    lastupdated: PropertyRef = PropertyRef("lastupdated", set_in_kwargs=True)


@dataclass(frozen=True)
# (:TailscaleTailnet)-[:RESOURCE]->(:TailscalePostureIntegration)
class TailscalePostureIntegrationToTailnetRel(CartographyRelSchema):
    """Defines the RESOURCE relationship to TailscaleTailnet nodes."""

    target_node_label: str = "TailscaleTailnet"
    target_node_matcher: TargetNodeMatcher = make_target_node_matcher(
        {"id": PropertyRef("org", set_in_kwargs=True)},
    )
    direction: LinkDirection = LinkDirection.INWARD
    rel_label: str = "RESOURCE"
    properties: TailscalePostureIntegrationToTailnetRelProperties = (
        TailscalePostureIntegrationToTailnetRelProperties()
    )


@dataclass(frozen=True)
class TailscalePostureIntegrationSchema(CartographyNodeSchema):
    """A configured PostureIntegration."""

    label: str = "TailscalePostureIntegration"
    properties: TailscalePostureIntegrationNodeProperties = (
        TailscalePostureIntegrationNodeProperties()
    )
    sub_resource_relationship: TailscalePostureIntegrationToTailnetRel = (
        TailscalePostureIntegrationToTailnetRel()
    )
